### ISSUE TITLE
Test user password

### ISSUE THREAD

**Issue by hbulens** [robdmoore/AzureAdMvcExample#1]
The following test users cannot be accessed anymore on the example site:

username1@azureadmvcexample.onmicrosoft.com with password P@ssword2, which is a member of Group 1 and Group 2

username2@azureadmvcexample.onmicrosoft.com with password P@ssword2, which is a member of Group 2 and Group 3

Could you update the new passwords in the documentation?

**Comment by robdmoore** [comment]
I updated back to reflect what's in doco.

The problem is by default there is a 90 day expiry.

I can turn that off as per https://azure.microsoft.com/en-us/documentation/articles/active-directory-passwords-set-expiration-policy/, but I wasn't having any luck using the PowerShell commandlets :(

**Comment by soonuu** [comment]
The given password is not working. Could you update the new passwords in the documentation?
